
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_500.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_501.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_502.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_503.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_504.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_505.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_506.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_507.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_508.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_509.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_511.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_510.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_512.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_513.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_514.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_515.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_516.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_517.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_518.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_519.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_520.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_521.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_522.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_525.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_524.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_523.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_526.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_527.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_528.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_529.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_530.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_532.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_531.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_533.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_534.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_535.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_536.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_537.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_538.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_539.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_540.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_541.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_543.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_542.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_544.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_545.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_546.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_547.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_548.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_549.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_550.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_551.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_552.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_553.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_554.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_555.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_556.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_557.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_558.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_559.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_560.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_561.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_562.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_564.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_563.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_565.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_566.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_567.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_568.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_569.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_570.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_571.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_572.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_573.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_574.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_575.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_576.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_577.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_578.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_579.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_580.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_581.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_582.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_584.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_583.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_585.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_587.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_586.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_588.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_589.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_590.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_591.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_592.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_593.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_594.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_595.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_596.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_597.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_598.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_599.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_600.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_601.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_602.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_603.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_604.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_605.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_606.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_607.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_608.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_609.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_610.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_611.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_613.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_612.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_614.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_615.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_616.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_617.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_618.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_619.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_620.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_621.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_622.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_623.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_624.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_625.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_626.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_627.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_628.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_629.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_630.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_631.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_632.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_634.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_635.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_633.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_636.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_637.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_638.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_639.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_640.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_641.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_642.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_644.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_643.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_646.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_648.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_647.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_645.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_649.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_650.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_651.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_652.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_653.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_654.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_655.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_656.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_657.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_658.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_659.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_660.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_661.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_662.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_663.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_664.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_665.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_667.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_668.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_669.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_670.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_666.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_671.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_673.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_672.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_674.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_675.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_676.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_677.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_678.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_679.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_680.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_681.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_682.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_683.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_684.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_685.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_686.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_687.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_688.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_689.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_691.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_692.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_690.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_693.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_694.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_696.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_695.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_697.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_698.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_699.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_700.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_701.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_702.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_703.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_705.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_704.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_706.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_707.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_708.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_709.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_710.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_711.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_712.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_713.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_714.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_715.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_716.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_717.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_718.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_719.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_720.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_721.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_722.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_723.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_724.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_725.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_726.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_727.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_728.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_729.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_730.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_731.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_732.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_733.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_734.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_735.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_736.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_737.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_738.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_739.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_740.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_741.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_742.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_743.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_744.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_745.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_746.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_747.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_748.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_749.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_750.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_751.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_752.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_753.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_754.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_755.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_756.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_757.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_758.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_759.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_760.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_761.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_762.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_763.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_764.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_765.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_766.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_767.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_768.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_769.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_770.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_771.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_772.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_774.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_773.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_775.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_777.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_776.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_778.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_779.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_780.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_781.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_782.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_783.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_784.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_785.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_786.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_787.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_788.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_789.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_790.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_791.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_792.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_793.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_794.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_795.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_796.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_797.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_798.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_799.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_800.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_801.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_802.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_803.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_804.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_805.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_806.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_807.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_808.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_809.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_810.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_811.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_812.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_813.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_814.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_815.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_816.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_817.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_818.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_819.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_820.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_821.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_822.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_823.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_824.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_825.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_826.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_827.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_828.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_829.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_830.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_831.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_832.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_833.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_834.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_835.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_836.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_837.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_838.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_839.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_840.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_841.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_842.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_843.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_844.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_845.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_846.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_847.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_848.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_850.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_849.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_851.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_852.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_853.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_854.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_855.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_856.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_858.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_857.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_859.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_860.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_861.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_863.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_862.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_864.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_865.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_866.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_867.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_868.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_870.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_869.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_871.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_872.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_873.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_874.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_875.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_876.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_877.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_878.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_879.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_880.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_881.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_882.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_883.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_884.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_885.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_886.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_887.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_888.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_889.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_890.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_892.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_891.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_893.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_894.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_895.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_896.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_897.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_898.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_899.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_900.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_901.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_902.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_903.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_904.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_905.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_906.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_907.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_908.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_910.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_909.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_911.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_912.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_913.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_914.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_915.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_916.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_917.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_918.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_919.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_920.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_921.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_922.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_923.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_924.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_925.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_926.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_927.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_928.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_929.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_930.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_931.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_932.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_933.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_934.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_935.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_936.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_937.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_938.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_939.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_940.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_941.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_942.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_944.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_945.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_943.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_946.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_947.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_948.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_949.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_950.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_951.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_952.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_953.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_954.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_955.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_956.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_957.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_958.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_959.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_960.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_961.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_962.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_963.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_964.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_965.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_966.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_967.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_968.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_969.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_970.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_971.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_972.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_973.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_974.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_975.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_976.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_977.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_978.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_979.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_980.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_981.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_982.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_983.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_984.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_985.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_986.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_987.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_988.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_990.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_989.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_991.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_992.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_993.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_994.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_995.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_996.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_997.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_998.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_synlarge/synlarge_999.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-6