julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/DUAL4.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LISWET7.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSCFXM1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/AUG2D.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/AUG2DC.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/AUG2DCQP.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/AUG2DQP.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/AUG3D.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/AUG3DC.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/AUG3DCQP.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/AUG3DQP.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/BOYD1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/BOYD2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CONT-100.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CONT-101.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CONT-200.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CONT-201.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CONT-300.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CVXQP1_L.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CVXQP1_S.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CVXQP2_L.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CVXQP2_M.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CVXQP2_S.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CVXQP3_L.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CVXQP3_M.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/CVXQP3_S.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/DPKLO1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/DTOC3.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/DUAL1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/DUAL2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/DUAL3.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LISWET8.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LISWET9.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LOTSCHD.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/MOSARQP1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/MOSARQP2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/PRIMAL1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/PRIMAL3.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/PRIMAL4.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/PRIMALC1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/PRIMALC2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/PRIMALC5.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/PRIMALC8.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/Q25FV47.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QADLITTL.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QAFIRO.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QBANDM.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QBEACONF.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QBORE3D.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QBRANDY.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QCAPRI.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QE226.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QETAMACR.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QFFFFF80.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QFORPLAN.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QGFRDXPN.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QGROW22.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QGROW7.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QISRAEL.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QPCBLEND.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QPCBOEI1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QPCBOEI2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QPCSTAIR.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QPTEST.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QRECIPE.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSC205.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSCAGR25.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSCFXM2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSCFXM3.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSCRS8.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSCSD1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSCSD6.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSCSD8.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSCTAP1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSCTAP2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSEBA.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSHARE1B.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSHARE2B.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSHELL.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSHIP04L.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSHIP04S.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSHIP08L.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSHIP08S.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSHIP12S.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSTAIR.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/QSTANDAT.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/S268.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/STADAT1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/STADAT2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/STCQP1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/STCQP2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/TAME.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/UBH1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/VALUES.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/YAO.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/ZECEVIC2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/DUALC1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/DUALC2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/DUALC5.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/DUALC8.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/EXDATA.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/GENHS28.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/GOULDQP2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/HS118.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/HS21.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/HS268.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/HS35.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/HS35MOD.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/HS51.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/HS52.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/HS53.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/HS76.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/HUES-MOD.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/HUESTIS.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/KSIP.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LASER.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LISWET1.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LISWET10.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LISWET11.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LISWET12.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LISWET2.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LISWET3.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LISWET5.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
julia scripts/solve_save.jl --instance_path=../../../ins/gen_train_mm/LISWET6.mps --output_directory=../../../logs --time_sec_limit=3600 --solve=1 --checkiter=5  --tolerance=1e-5
