cd ../src;
python train_new.py -t netlib_gnnk1 -m 2000;
python predict_new.py -t netlib_gnnk1;
cd ./julia/PDLP;
python gen_bat.py -t netlib_test -o 1 -e netlib_gnnk1_s0;
bash run_test.bat;
cd ../../logs;
python analyze.py -t netlib -e netlib_gnnk1_s0;
cd ../../script;
cd ../src;
python train_new.py -t netlib_gnnk2 -m 2000;
python predict_new.py -t netlib_gnnk2;
cd ./julia/PDLP;
python gen_bat.py -t netlib_test -o 1 -e netlib_gnnk1_s1;
bash run_test.bat;
cd ../../logs;
python analyze.py -t netlib -e netlib_gnnk1_s1;
cd ../../script;
cd ../src;
python train_new.py -t netlib_gnnk3 -m 2000;
python predict_new.py -t netlib_gnnk3;
cd ./julia/PDLP;
python gen_bat.py -t netlib_test -o 1 -e netlib_gnnk1_s2;
bash run_test.bat;
cd ../../logs;
python analyze.py -t netlib -e netlib_gnnk1_s2;
cd ../../script;
cd ../src;
python train_gnn.py -t netlib_gnn_sup -m 2000;
python predict_gnn.py -t netlib_gnn_sup;
cd ./julia/PDQP.jl;
python gen_bat.py -t netlib_test -o 1 -e netlib_gnn_sup_s0;
bash run_test.bat;
cd ../../logs;
python analyze.py -t netlib -e netlib_gnn_sup_s0;
cd ../../script;