cd ../src;
python reshufflepkl.py -s 0 -t mm;
python train_gnn.py -t mm_gnn_sup -m 300;
python predict_gnn.py -t mm_gnn_sup;
cd ./julia/PDQP.jl;
python gen_bat.py -t mm_test -o 1 -e mm_gnn_sup_s0;
bash run_test.bat;
cd ../../logs;
python analyze.py -t mm -e mm_gnn_sup_s0;
cd ../../script;
cd ../src;
python reshufflepkl.py -s 1 -t mm;
python train_gnn.py -t mm_gnn_sup -m 300;
python predict_gnn.py -t mm_gnn_sup;
cd ./julia/PDQP.jl;
python gen_bat.py -t mm_test -o 1 -e mm_gnn_sup_s1;
bash run_test.bat;
cd ../../logs;
python analyze.py -t mm -e mm_gnn_sup_s1;
cd ../../script;
cd ../src;
python reshufflepkl.py -s 2 -t mm;
python train_gnn.py -t mm_gnn_sup -m 300;
python predict_gnn.py -t mm_gnn_sup;
cd ./julia/PDQP.jl;
python gen_bat.py -t mm_test -o 1 -e mm_gnn_sup_s2;
bash run_test.bat;
cd ../../logs;
python analyze.py -t mm -e mm_gnn_sup_s2;
cd ../../script;